<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Challenge___Maze_Generation</RootNamespace>
    <AssemblyName>Challenge - Maze Generation</AssemblyName>
    <ApplicationIcon>icon rose.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
