<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Challenge___Pathfinding</RootNamespace>
    <AssemblyName>Challenge - Pathfinding</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
