<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ASCII_Art_Renderer</RootNamespace>
    <AssemblyName>ASCII Art Renderer</AssemblyName>
    <ApplicationIcon>hnet.com-image.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
