<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Game___Tetris</RootNamespace>
    <AssemblyName>Game - Tetris</AssemblyName>
    <ApplicationIcon>icon rose.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
