<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Game_Of_Life_Simulation</RootNamespace>
    <AssemblyName>Game Of Life Simulation</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
