//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Games.Sokoban.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Games.Sokoban.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection: Original Extra Sharpen
        ///Author: DrFogh, Archanfel and Joseph L Traub
        ///Mail: bjertrup58@gmail.com
        ///Url: www.sokoban.dk
        ///Date_First: 2017-09-09
        ///Date_Last: 2017-10-08
        ///
        ///Sharpened and reduced versions of all of the levels 51-90 in the
        ///collection &quot;Original Plus Extra&quot;.
        ///The levels were originally collected and/or made by Joseph Traub and
        ///others and supplied with the XSokoban player.
        ///The changes here are mostly by me (DrFogh).
        ///With lots of changes and levels added by Archanfel.
        ///More about the p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrFogh_Archanfel_and_Joseph_L_Traub_Original_Extra_Sharpen {
            get {
                return ResourceManager.GetString("DrFogh_Archanfel_and_Joseph_L_Traub_Original_Extra_Sharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection: It Is All Greek
        ///Author: DrFogh
        ///E-mail: bjertrup58@gmail.com
        ///URL: www.sokoban.dk
        ///Published: 2019-02-24
        ///Date_First: 2017-06-24
        ///Date_Last: 2017-12-01
        ///
        ///Download and play as you wish.
        ///Don&apos;t publish uninteresting variations. You are the judge.
        ///Give proper credit.
        ///Free to publish.
        ///
        ///Right through the greek alphabeth. You only need to get one box to its
        ///goal so that should be easy.
        ///The goal with this collection was to construct the levels so it
        ///is necessary to move all the boxes to solve  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrFogh_It_Is_All_Greek_Publish {
            get {
                return ResourceManager.GetString("DrFogh_It_Is_All_Greek_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection: Numbers
        ///Author: DrFogh
        ///Email: bjertrup58@gmail.com
        ///URL: www.sokoban.dk
        ///Firstdate: 2016-06-20
        ///Lastdate: 2016-08-28
        ///
        ///First published at www.sokoban.dk
        ///
        ///These puzzles can be freely distributed. 
        ///
        ///Please quote me as the original author with name, email and url.
        ///DrFogh
        ///
        ///-#####
        ///##---#
        ///#----##
        ///#--#--#
        ///#-$#-.###
        ///#--#*.--#
        ///#-$-$.--#
        ///#--#$.###
        ///####-.#
        ///--##$.#
        ///--#-$*#
        ///--#--@#
        ///--#####
        ///Title: One
        ///Date: 2016-06-21
        ///
        ///-#####
        ///-#---######
        ///-#-#**----#
        ///-#-.--*-#-#
        ///-#-$--*-#-#
        ///-#### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrFogh_Numbers {
            get {
                return ResourceManager.GetString("DrFogh_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection: Original02
        ///Author: DrFogh
        ///Mail: bjertrup58@gmail.com
        ///Url: www.sokoban.dk
        ///FirstDate: 2015-11-21
        ///LastDate: 2016-06-29
        ///
        ///50 original puzzles arranged roughly chronologically.
        ///A few previously published variations only differing slightly from the puzzles here are omitted.
        ///The puzzles can be freely distributed.
        ///Dont remodel or sharpen anything unless it is obviously good.
        ///I am the judge on that. 
        ///
        ///Regards 
        ///DrFogh
        ///
        ///-----#####
        ///######---##
        ///#---$.$---#
        ///#-#$#.#$#-#
        ///#--..+..#-#
        ///#-#$#.#$ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrFogh_Original_02 {
            get {
                return ResourceManager.GetString("DrFogh_Original_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection: Original 3
        ///Author: DrFogh
        ///Mail: bjertrup58@gmail.com
        ///Url: www.sokoban.dk
        ///FirstDate: 2016-08-19
        ///LastDate: 2017-12-14
        ///Published: 2020-03-30
        ///
        ///50 original levels arranged roughly chronologically.
        ///A few previously published variations are omitted only differing 
        ///slightly from the levels in this collection.
        ///
        ///Most published at www.sokoban.dk
        ///These levels can be freely distributed.
        ///Please quote me as the original author with name, email and url.
        ///DrFogh
        ///
        ///#############
        ///#----####---#
        ///#-- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrFogh_Original_3 {
            get {
                return ResourceManager.GetString("DrFogh_Original_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection: Original01
        ///Author: DrFogh
        ///Mail: bjertrup58@gmail.com
        ///Url: www.sokoban.dk
        ///Firstdate: 2013-07-31
        ///Lastdate: 2015-11-19
        ///
        ///50 original puzzles arranged roughly chronologically.
        ///A few previously published variations only differing slightly from the puzzles here are omitted.
        ///
        ///The puzzles can be freely distributed. 
        ///
        ///Plese quote me as the original author with name, email and url.
        ///
        ///###########
        ///#---------#
        ///#-$-$@$-$-#
        ///#--$-$-$--#
        ///#-$-$-$-$-#
        ///#--$-$-$--#
        ///#####$##$##
        ///-#.....#-#
        ///-#....*# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrFogh_Original01 {
            get {
                return ResourceManager.GetString("DrFogh_Original01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection: Sokobet
        ///Author: DrFogh
        ///Email: bjertrup58@gmail.com
        ///URL: www.sokoban.dk
        ///Firstdate: 2015-09-05
        ///Lastdate: 2015-11-14
        ///
        ///Right through the alfabet. Because it is the danish alfabet, you will get a few bonus levels.
        ///
        ///These puzzles can be freely distributed.
        ///
        ///Plese quote me as the original author with name, email and url.
        ///
        ///-------############
        ///-#######--#---#---#
        ///-#--------#-----#-##
        ///-#--$-###-##-#.----#
        ///###$#$----##-.-.---#
        ///#--$-$-#-----.#.---#
        ///#@$---$#####.###.###
        ///#-$$$$$----#.....# [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DrFogh_Sokobet_1 {
            get {
                return ResourceManager.GetString("DrFogh_Sokobet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
        ///::         Sokoban (c) by Falcon Co., Ltd., Japan         ::
        ///::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
        ///::                    File Format 0.17                    ::
        ///::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
        ///::                                                        ::
        ///:: File Notes                                  Optional   ::
        ///:: Puzzle 1                                    Required   ::
        ///::    Title      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtremelyEasy {
            get {
                return ResourceManager.GetString("ExtremelyEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection: Set 4
        ///Author: Howard Abed
        ///Copyright: Howard Abed
        ///E-Mail: Howard1818@cs.com
        ///
        ///All the levels in set 1, 2 &amp; 3 are my design and the are copyright,
        ///You can play them but NOT to sell them,
        ///
        ///This set is my edit for few of the levels
        ///I delete unnecessary space and add more boxes
        ///
        ///Comments by DrFogh 2017  
        ///
        ///----#####
        ///----#---#
        ///----#$--#
        ///--###--$##
        ///--#--$-$-#
        ///###-#-##-#---######
        ///#---#-##-#####-...#
        ///#-$--$---@---$-...#
        ///##############-$..#
        ///-------------######
        ///Title: 01 HA
        ///Comment: A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Howard_Abed_Set_4 {
            get {
                return ResourceManager.GetString("Howard_Abed_Set_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection: Original Plus Extra
        ///Author: Thinking Rabbit
        ///Copyright: Thinking Rabbit
        ///Date: 1988
        ///Last change: 2017-08-30
        ///
        ///The original levels by Thinking Rabbit for the first english version
        /// of Sokoban, Soko-Ban published by Spectrum Holobyte in 1988.
        ///The original levels came from Thinking Rabbits Sokoban(1982), 
        ///Sokoban2(1984) and a few from SokobanMSX(1984)
        ///Some of the levels were modified slightly by Spectrum Holobyte for 
        ///various reasons.
        ///Some of the levels were modified when the levelset were [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Thinking_Rabbit_Original_Plus_Extra {
            get {
                return ResourceManager.GetString("Thinking_Rabbit_Original_Plus_Extra", resourceCulture);
            }
        }
    }
}
