<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Game_Tick_Boilerplate</RootNamespace>
    <AssemblyName>Game-Tick-Boilerplate</AssemblyName>
    <ApplicationIcon>icon rose.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
